[build]
  publish = "public" # Cambia in "dist" se usi un sistema di build
  # Comando per la build (se necessario)
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173 # Se usi Vite, altrimenti cambia con il tuo

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
