[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Forza Netlify a copiare la cartella public
[build.processing]
  skip_processing = false

[[plugins]]
  package = "@netlify/plugin-local-install"

[build.environment]
  VITE_PUBLIC_PATH = "/"
